---
:concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 20 %>
:queues:
  - [low,      1]
  - [default,  2]
  - [search_sync, 2]
  - [medium,   3]
  - [high,     4]
  - [urgent,   5]
  - [critical, 6]
